<a href="https://colab.research.google.com/github/kartik-tiwariR20/starting-pytorch/blob/main/pytorchs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
np1 = np.random.rand(4,5)
np1
np1.dtype

dtype('float64')

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 8.3748e-01,  1.5498e-01, -6.2563e-01, -1.5716e+00],
        [ 1.1444e+00, -3.6088e-01,  8.6901e-01, -4.7726e-01],
        [-1.9481e-03,  1.9302e+00,  2.1407e+00,  1.4567e+00]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7494, 0.5094, 0.0952, 0.9241, 0.3357],
        [0.1757, 0.9514, 0.6929, 0.5878, 0.8595],
        [0.0039, 0.5594, 0.2574, 0.0205, 0.2791],
        [0.4624, 0.7567, 0.2672, 0.1534, 0.1979]], dtype=torch.float64)